pull_request_rules:
  - name: Automatic approve Dependabot pull requests
    conditions:
      - author~=dependabot\[bot\]|dependabot-preview\[bot\]
      - status-success=Linting - Check Style
    actions:
      review:
        type: APPROVE

  - name: Write issue comment to start codebuild project
    conditions:
      - author~=dependabot\[bot\]|dependabot-preview\[bot\]
      - "#approved-reviews-by>=1"
    actions:
      comment:
        message: go codebuild go
        
  - name: Automatic merge Dependabot pull requests
    conditions:
      - author~=dependabot\[bot\]|dependabot-preview\[bot\]
      - status-success=Linting - Check Style
      - status-success=codebuild/tml-test-webhook/pr
    actions:
      merge:
        method: merge