---
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "Entered the install phase..."
      - apt-get update -y
  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
  build:
    commands:
      - echo "Entered the build phase..."
      - echo "Build started on `date`"